### PR TITLE
Hack WIP: In place relay experiment

### PR DESCRIPTION
**Pull request by Raynos**
I wanted to experiment with what is the maximum performance we can get out of an in place relay code.

Joshua is working hard #911 which does in place relaying properly using lazy frames.

This branch will **never be landed**. The only purpose of this hack is to find out what a minimal relay looks like and what else except relaying is slow in tchannel.

 - [x] hack fast in place relay to be replaced by #911 
 - [x] hack fast choosePeer to be replaced by #915 
 - [x] multi process benchmark to find actual req/s
 - [ ] hack faster ops to waste less time in timers
 - [ ] hack faster `net` code to remove wasted time in the tcp code.

### CODE REVIEW

**Comment by Raynos** [comment]
https://people.uberinternal.com/~jakev/in_place_relay_flame.svg

I have a flame demonstrating that with in place relaying the CPU is completely dominated by actual TCP IO stuff.

**Comment by Raynos** [comment]
```
raynos at raynos-SVS15127PXB  ~/uber/tchannel/node/benchmarks on in-place-relay*
$ node compare.js relay-multi-proc-benchmark.json relay-aeff890.json 
GET 16KiB, 1000/0  rate: hi-diff:   3553.32 (146.7%)
GET 16KiB, 10000/0 rate: hi-diff:   3355.94 (145.9%)
GET 16KiB, 20000/0 rate: hi-diff:   3612.93 (176.2%)
GET 4B, 1000/0     rate: hi-diff:   3831.15 (144.3%)
GET 4B, 10000/0    rate: hi-diff:   3886.82 (145.1%)
GET 4B, 20000/0    rate: hi-diff:   4451.21 (169.1%)
GET 4KiB, 1000/0   rate: hi-diff:   3493.20 (148.7%)
GET 4KiB, 10000/0  rate: hi-diff:   3561.75 (138.2%)
GET 4KiB, 20000/0  rate: hi-diff:   4876.17 (230.6%)
PING, 1000/0       rate: hi-diff:   3637.61 (105.3%)
PING, 10000/0      rate: hi-diff:   3945.39 (137.3%)
PING, 20000/0      rate: hi-diff:   4323.52 (156.5%)
SET 16KiB, 1000/0  rate: hi-diff:   3707.77 (161.6%)
SET 16KiB, 10000/0 rate: hi-diff:   3138.08 (140.8%)
SET 16KiB, 20000/0 rate: hi-diff:   3894.38 (171.3%)
SET 4B, 1000/0     rate: hi-diff:   3918.60 (136.5%)
SET 4B, 10000/0    rate: hi-diff:   3887.46 (141.7%)
SET 4B, 20000/0    rate: hi-diff:   4368.01 (160.8%)
SET 4KiB, 1000/0   rate: hi-diff:   4298.07 (211.3%)
SET 4KiB, 10000/0  rate: hi-diff:   3852.14 (169.3%)
SET 4KiB, 20000/0  rate: hi-diff:   4554.00 (190.1%)
```

I ran the numbers and this is the maximum we can get it out of; its about 2-3x performance increase.

**Comment by Raynos** [comment]
Here is a flame for those numbers

https://people.uberinternal.com/~jakev/in_place_relay_flame.svg

As you can see all the CPU is just networking stuff.

**Comment by Raynos** [comment]
This experiment has served its purpose.

**Comment by kriskowal** [comment]
I am in favor of this approach, perhaps even over the approach of generalizing lazy RWs. I do not think we are going to need the flexibility of RW objects for relaying since the protocol itself is not that flexible. This is farther along the road to eliminating GC churn and probably gets us within 4x of our 20krps design goal.

**Comment by Raynos** [comment]
@kriskowal 

I'm in favor of a minimal approach. However we still need to create InReq and OutReq data structures to track timeouts, stats & circuit health. All of which I've avoided.

**Pull request closed without merging**
