### PR TITLE
Examples should use 0.0.0.0 for portability

### PR DESCRIPTION
**Pull request by breerly**
This change is needed for the tchannel-testbed I'm working on - the examples get installed into containers, which need to be accessible outside of themselves.

### CODE REVIEW

**Comment by breerly** [comment]
Looks like the node implementation doesn't like `0.0.0.0` as an address to listen on:

```
if (host === '0.0.0.0') {
     throw new Error('TChannel must listen with externally visible host'); // TODO typed error
}
```
@jcorbin @Raynos any idea how I can get the node examples accessible from outside the same box? With the python example, switching to `0.0.0.0` has the affect of allowing requests from anywhere.

**Comment by Raynos** [comment]
@breerly `npm i my-local-ip` ( https://github.com/dominictarr/my-local-ip ).

This will grab the external; non localhost IP that you can listen to.

**Comment by jcorbin** [comment]
@breerly listening on `0.0.0.0` is an anti pattern that we don't want to encourage, let's:
- [ ] drop the `.listen()` from all example clients now that we have ephemeral semantics
- [ ] use explicit IPs, either loopback or discovered, for example server

**Comment by kriskowal** [comment]
Closing. Tracking follow-up on #505

**Pull request closed without merging**
