### PR TITLE
Speed up Travis.

### PR DESCRIPTION
**Pull request by breerly**
Travis is taking a long time. This is for many reasons.

* We are not caching anything installed  by npm & pip.
* Tox runs in serial for every version of Python.
* We run python tests even when we dont edit that directory (same for node).

### CODE REVIEW

**Comment by kriskowal** [comment]
This is good magic. The same magic could probably be performed for the ~/.npm cache.

**Comment by breerly** [comment]
I think our biggest gains, in order, will be:

1. Allowing Tox to run in parallel.
2. Add caching for NPM & pip.
3. Figuring out if we can not run a certain languages test suite if there were no changes.

**Comment by breerly** [comment]
Upgraded concurrent jobs from 0 to 100 in settings:

screen shot 2015-03-16 at 5 31 24 pm

**Comment by Raynos** [comment]
lgtm.

**Comment by breerly** [comment]
This is ready to go - build takes around ~1 min now.

**Comment by Raynos** [comment]
<3

**Pull request merged**
