### PR TITLE
Add a waitForIdentified method + friends

### PR DESCRIPTION
**Pull request by Raynos**
This PR adds:

 - waitForIdentified method; used by other libraries that want
    to do direct peer to peer requests without using `node/request.js` 
 - Fix a bug in connection.js
 - Fix hyperbahn to wait for identification
 - Add a timeout to hyperbahn
 - Change the timeout reaper in tchannel to use 100ms

r: @kriskowal @shannili @rf

### CODE REVIEW

**Comment by Raynos** [comment]
This is necessary to go in today to unblock autobahn & pals.

**Comment by kriskowal** [comment]
I believe that there is an outstanding issue recommending this feature by
the name withConnection.

**Comment by Raynos** [comment]
I'm open to a rename; i don't care. Whoever renames it has to autobahn and redeploy autobahn though.

**Comment by ShanniLi** [comment]
lgtm :)

**Pull request merged**
