### PR TITLE
add ping payloads

### PR DESCRIPTION
**Pull request by blampe**
tcap isn't able to show these frames because tchannel doesn't know how to parse type codes `0xd0` and `0xd1`. These don't have bodies and so I think `skip(0)` is right but I'm not sure how the `write` method should look. @jcorbin thoughts?

cc @kriskowal

### CODE REVIEW

**Comment by jcorbin** [comment]
Needs a test, but otherwise this could be a step towards #124

**Comment by kriskowal** [comment]
I’ve taken this a step further, though sideways, perhaps not toward landing but toward exploring. I’ve added lib/read,write "null" frame reader and writer. These have already been implemented with the "null" reader and writer in bufrw, which will replace lib/read,write.js. I also wrote out some scaffolding and TODOs for the ping request and response handler, which raise some questions. Does the incoming ping request handler have enough on hand to construct a ping response and send it back on the channel from which it came? Do we need to generalize the incoming request and response handler methods such that they do not depend on a call request/response body, or should we split those methods into call and ping variations? Both rely on a frame identifier to handler mapping.

**Comment by breerly** [comment]
Should this be merged or closed? Lets act :)

**Comment by blampe** [comment]
Not worrying about this right now, we can re-visit when we start caring more about pings.

**Comment by breerly** [comment]
Closing for now - will stay available here:

https://github.com/uber/tchannel/pulls?q=is%3Apr+is%3Aclosed

**Pull request closed without merging**
