### PR TITLE
Update http error mapping doc

### PR DESCRIPTION
**Pull request by anson627**
r: @ShanniLi @jcorbin @Raynos 
cc: @gshu @Matt-Esch

### CODE REVIEW

**Comment by jcorbin** [comment]
lgtm, however I would suggest varying the status message meaningfully fwiw.  I.e. "500 TChannel Network Error" "500 TChannel Protocol Error" "500 Cancelled" etc...

**Comment by ShanniLi** [comment]
lgtm. :+1: @jcorbin, specific messages will be more clear.

**Comment by anson627** [comment]
agree. The concern is assigning different message to same status code seems to be inconsistent with the standard.

**Comment by jcorbin** [comment]
Not so @anson627 , http status messages have always had only "suggested defaults" only; returning semantically meaningful status messages has always been A Thing in http (an/the entire point of separating out standard codes, is so that you can change the message ;-) ).

**Comment by anson627** [comment]
done with specific messages.

**Pull request merged**
