### PR TITLE
StreamingIn{Request,Response}: error if arg1 is fragmented

### PR DESCRIPTION
**Pull request by jcorbin**
Making it an error ahead of dropping support in #1040 

r @kriskowal @Raynos

### CODE REVIEW

**Comment by Raynos** [comment]
Can we get a regression test ?

**Comment by kriskowal** [comment]
:ok:

**Comment by anson627** [comment]
Can we fix this as well?

as/http.js line 294 ~ 299
    // TODO: real soon arg1 won't be streamable / fragmentable
    if (req.streamed) {
        req.arg1.onValueReady(onArg1);
    } else {
        onArg1(null, req.arg1);
    }

**Comment by jcorbin** [comment]
Good point @anson627 , I'll fix that in #1040 when I actually drop support for it entirely and deprecate the arg1 waiting functions.

**Comment by kriskowal** [comment]
:ok:

**Pull request merged**
