### PR TITLE
Set response code to error when exceptions happen in thrift server

### PR DESCRIPTION
**Pull request by junchaowu**
@blampe @abhinav @breerly 
Fix https://github.com/uber/tchannel/issues/894#issuecomment-119755493

### CODE REVIEW

**Comment by blampe** [comment]
Needs a test.

**Comment by junchaowu** [comment]
It has been tested. If the code is incorrect , the test_thrift_exception test won't pass

**Comment by blampe** [comment]
If you make code changes without touching a test, then none of our tests were asserting anything about the behavior you changed...

**Comment by junchaowu** [comment]
No. Take a look at the test_thrift_exception test. Previously client code doesn't check the response code that's why the test will pass even if we don't set right response code. Now I add it. So if client throws an thrift exception, it must get 'error' response code.

**Comment by blampe** [comment]
:+1: thanks for the regression test @abhinav

**Pull request merged**
