### PR TITLE
channel: downgrade connection timeouts to warnings

### PR DESCRIPTION
**Pull request by Raynos**
Connection timeout errors are not errors; downgrading them
to warnings.

r: @shannili @rf

### CODE REVIEW

**Comment by anson627** [comment]
more of a question, why timeout is a warning instead of error?

**Comment by Raynos** [comment]
Timeouts are normal operational errors.

Operational errors are warnings.

Programmer errors and unexpected errors are bugs and should be logger.error()

**Comment by rf** [comment]
:+1:

**Comment by anson627** [comment]
good to know! I thought unexpected errors are categorized as fatal. Error is something we already know.

**Pull request merged**
