### PR TITLE
No more arg1 streaming

### PR DESCRIPTION
**Pull request by jcorbin**
Towards #911, and a pre-req of #1038

Drops support for arg1 streaming.

r @kriskowal

### CODE REVIEW

**Comment by jcorbin** [comment]
Okay dear reviewers, should I:
- leave `req.withArg1((err, arg1) -> void)` for *hand wave* external compatability
- or should I say "the external layer are the as handlers, so let's drop the old path"?

**Comment by kriskowal** [comment]
@jcorbin leave the thunk. I don’t want surprises.

**Comment by jcorbin** [comment]
Understood, added deprecation comments at least

**Comment by kriskowal** [comment]
:ok: Full of win.

**Comment by Raynos** [comment]
noice.

**Comment by Raynos** [comment]
@jcorbin please update https://github.com/uber/tchannel/blob/master/node/docs/streaming.md

Just need to change docs to mention buffers instead of streams.

**Comment by Raynos** [comment]
Also because `Stability: unstable` this is not a major bump; probably a minor bump though.

**Pull request merged**
