### PR TITLE
add meta.thrift to tchannel

### PR DESCRIPTION
**Pull request by ShanniLi**
r @Raynos @kriskowal @rf

### CODE REVIEW

**Comment by rf** [comment]
lgtm

**Comment by kriskowal** [comment]
This is the not the interface I believe emerged from the last offline discussion. I believe we had universal agreement to:

```thrift
struct Health {
   1: required bool ok
   2: optional string message
}
service Meta {
    Healthy health()
}
```

Or words to that effect

**Comment by ShanniLi** [comment]
@kriskowal good catch! Looking ...

**Comment by ShanniLi** [comment]
@kriskowal fixed.

**Comment by kriskowal** [comment]
:ok:

**Pull request merged**
