### PR TITLE
Cut Python TChannel 0.5.0

### PR DESCRIPTION
**Pull request by breerly**

### CODE REVIEW

**Comment by abhinav** [comment]
:+1:

**Comment by abhinav** [comment]
:shipit:

**Comment by abhinav** [comment]
Go go go

**Comment by breerly** [comment]
@abhinav I removed futures as a dependency. Is there anything else that can go?

**Comment by breerly** [comment]
@junchaowu @abhinav please write out a short changelog that I can use for the changelog :)

**Comment by abhinav** [comment]
I think the rest of the dependencies are required.

No changelog. We've made a number of API changes since last release. I don't think anyone kept track.

**Comment by breerly** [comment]
Shouldn't we be adding tornado to requires?

**Comment by abhinav** [comment]
Might as well

**Pull request merged**
