### PR TITLE
readthedocs compatibility

### PR DESCRIPTION
**Pull request by blampe**
Preview of what this looks like: http://tchannel.readthedocs.org/en/docs/

Refs #934

### CODE REVIEW

**Comment by breerly** [comment]
super sweet

**Comment by abhinav** [comment]
I like the idea.

Minor changes:

I would put the protocol spec and all other details under the "Protocol" or "Specification" top-level title and still use a toctree of depth 2. This way our TOC looks like this:

* Specification
  * TChannel V2
  * HTTP over TChannel
  * JSON over TChannel
  * Thrift over TChannel
  * TChannel Traffic Metrics

(Also, yeah, move Thrift before metrics.)

Or maybe drop toctree depth to just 1. We can adjust these details later.

**Comment by Raynos** [comment]
@blampe lgtm.

**Comment by blampe** [comment]
Going to land this. The TOC is crowded but we can iterate on that.

**Pull request merged**
