### PR TITLE
Add and convert to a faster (custom) EventEmitter

### PR DESCRIPTION
**Pull request by jcorbin**
r @Raynos @kriskowal @mranney

### CODE REVIEW

**Comment by Raynos** [comment]
We should write a document somewhere how this EventEmitter has less features and what features we removed.

**Comment by Raynos** [comment]
Suggestions for shipping:

 - remove `once()`
 - add an `assert(type)` in `removeAllListeners()`

The rest of the feedback is either optional or later.

**Comment by jcorbin** [comment]
- fixed a few missed .on/.emit conversions
- dropped .once support entirely
- assert against .removeAllListeners without type

**Comment by Raynos** [comment]
lgtm.

**Comment by kriskowal** [comment]
:heart: explicit event declaration. :ok:

**Comment by jcorbin** [comment]
Okay finally slogged through more closure killing, and other ideas around this base class, we're now solidly faster:
```
tchannel/node node-v2.0.0-beta2-855-gaf88359 % node benchmarks/compare.js benchmarks/master.json benchmarks/event_emit_pocalypse_singleton.json
GET 16KiB, 1000/0  rate: hi-diff:   1557.38 ( 13.8%)
GET 16KiB, 10000/0 rate: hi-diff:   1142.36 ( 10.9%)
GET 16KiB, 20000/0 rate: hi-diff:   1291.72 ( 12.7%)
GET 4B, 1000/0     rate: hi-diff:   5121.46 ( 34.2%)
GET 4B, 10000/0    rate: hi-diff:   3913.99 ( 26.5%)
GET 4B, 20000/0    rate: hi-diff:   2183.40 ( 13.7%)
GET 4KiB, 1000/0   rate: hi-diff:    204.68 (  1.4%)
GET 4KiB, 10000/0  rate: hi-diff:   2676.65 ( 21.7%)
GET 4KiB, 20000/0  rate: hi-diff:   2659.43 ( 20.5%)
PING, 1000/0       rate: hi-diff:   5489.75 ( 37.1%)
PING, 10000/0      rate: hi-diff:   3729.13 ( 24.8%)
PING, 20000/0      rate: hi-diff:   4174.56 ( 26.3%)
SET 16KiB, 1000/0  rate: hi-diff:   1026.62 (  8.4%)
SET 16KiB, 10000/0 rate: hi-diff:    902.49 (  9.3%)
SET 16KiB, 20000/0 rate: hi-diff:   1191.00 ( 15.1%)
SET 4B, 1000/0     rate: hi-diff:   5914.77 ( 39.2%)
SET 4B, 10000/0    rate: hi-diff:   2246.55 ( 14.8%)
SET 4B, 20000/0    rate: hi-diff:   2417.61 ( 14.8%)
SET 4KiB, 1000/0   rate: hi-diff:   2516.26 ( 17.8%)
SET 4KiB, 10000/0  rate: hi-diff:   1742.63 ( 15.4%)
SET 4KiB, 20000/0  rate: hi-diff:   1072.92 (  8.6%)
```

**Comment by jcorbin** [comment]
Tests pass locally, will fail in travis because node 0.12.

Merging any we can improve via flaming and etc going forward.

**Pull request merged**
