### PR TITLE
Improve waitForIdentified

### PR DESCRIPTION
**Pull request by Raynos**
This should gaurd us against memory leaks.

r: @rf @kriskowal

### CODE REVIEW

**Comment by rf** [comment]
:+1:

**Comment by ShanniLi** [comment]
lgtm

**Comment by ShanniLi** [comment]
question:
when all connections of a peer get closed due to errors, will the peer be closed as well?

**Comment by Raynos** [comment]
@ShanniLi peers do not get closed; i fixed a seperate ephemeral peer leak in a seperate PR.

**Comment by kriskowal** [comment]
:+1:

**Pull request merged**
