### PR TITLE
v2/index: use a RetryFlags constructor

### PR DESCRIPTION
**Pull request by Raynos**
Creates a constructor for an anonymous object on the
hot code path.

r: @kriskowal @rf @shannili

### CODE REVIEW

**Comment by ShanniLi** [comment]
lgtm

**Comment by kriskowal** [comment]
My impression of this kind of change is that there is a hidden class for the options object regardless of whether you use an object literal or a constructor. You go faster only if code that uses the options object always receives the same hidden class (so it can compile down to accessing properties of a struct by consistent offsets). So, for this kind of change to be beneficial, there must be multiple sites where the same constructor is instantiated and code downstream must always receive that exact hidden class so it can remain optimized. Receiving a different hidden class would derail the optimization.

This optimization by itself should have no impact on performance.

**Comment by kriskowal** [comment]
:ok: in any case since it’s forward progress toward a potential optimization.

**Comment by Raynos** [comment]
@kriskowal The flames show speed up with a constructor.

**Pull request merged**
