### PR TITLE
WIP: Inline PassThrough, and kill the runtime require

### PR DESCRIPTION
**Pull request by jcorbin**
cc @anson627 this should cut out the runtime requires from your flame graphs

### CODE REVIEW

**Comment by Raynos** [comment]
Screw this. just `require('stream')`

Let's just drop readable-stream. Importing from node core is far simpler.

**Comment by jcorbin** [comment]
Okay, so we'll choose either this PR or #1179, let's see.

**Comment by jcorbin** [comment]
Closing but leaving the branch in place in case we need it.

**Comment by jcorbin** [comment]
So amusingly this branch ended up being ~5% faster (less latency) than #1179, so I might resurrect it in spirit by just writing a direct PassThrough replacement in one class...

**Pull request closed without merging**
