### PR TITLE
Converge on serviceName over service for requests

### PR DESCRIPTION
**Pull request by kriskowal**
Old and busted:
 - service meant service name
 - serviceObj meant service instance

New hawtness:
 - serviceName means service name
 - service means service instance

### CODE REVIEW

**Comment by kriskowal** [comment]
r @jcorbin @Raynos

**Comment by Raynos** [comment]
Rename of `serviceObj` to `service` does not help.

`service` is ambigious enough as it is; calling it `serviceObj` or something `serviceTuple` or whatever helps in this case.

**Comment by jcorbin** [comment]
lgtm

-1 on @Raynos 's serviceObj feedback, better to have `service` just be the danged "service" thing at hand

**Comment by Raynos** [comment]
Do we want to rename `v2.CallRequest.service` to `serviceName` as well ? at what point are we talking about the `service` field on the call request vs the `serviceName` ?

Should we go the other way and rename everything to `service` to have consistency with `v2.CallRequest`

**Comment by Raynos** [comment]
lgtm.

**Pull request merged**
