### PR TITLE
Make peers.delete() defensive

### PR DESCRIPTION
**Pull request by Raynos**
There are edge cases where we tried to delete non-existant
ephemeral peers.

r: @shannili @kriskowal

### CODE REVIEW

**Comment by ShanniLi** [comment]
lgtm

**Comment by ShanniLi** [comment]
shipit! gogogo

**Comment by breerly** [comment]
@ShanniLi this whole time I didn't realize it was you Juncao :P

**Comment by ShanniLi** [comment]
@breerly :)

**Pull request merged**
