### PR TITLE
Node: connection cleanup

### PR DESCRIPTION
**Pull request by Raynos**
Here's a little bit of cleanup work from the perf branch

r: @kriskowal @shannili @rf

### CODE REVIEW

**Comment by kriskowal** [comment]
:no_entry: More likely to harm than help performance, unless you’ve got conclusive numbers.

**Comment by ShanniLi** [comment]
lgtm

**Comment by Raynos** [comment]
I'll remove the string stuff; it does seem to hurt perf.

**Comment by kriskowal** [comment]
:bueno:

**Pull request merged**
