### PR TITLE
WIP: simplify req callback hookup

### PR DESCRIPTION
**Pull request by jcorbin**
r @kriskowal @Raynos

### CODE REVIEW

**Comment by Raynos** [comment]
lgtm

**Comment by kriskowal** [comment]
hookupCallback is an async analog to the sync result.toCallback. Perhaps they should have the same name.

**Comment by kriskowal** [comment]
This is stale. It needs a rebase and refactor in light of hookupStreamCallback having been implemented and Node.js Travis being fixed since.

**Comment by Raynos** [comment]
lgtm.

**Comment by jcorbin** [comment]
rebased, but not yet passing tests, needs a bit of reworking

**Comment by jcorbin** [comment]
it breaks tests, which is why it's limboing; I probably won't have time soon to complete it

**Comment by Raynos** [comment]
cool. lets limbo

**Comment by Raynos** [comment]
Having tried to rebase this code; this seems complicated. I'm worried that people are listening to the events directly; could not figure out why the tests are failing.

We might want to consider abandoning this optimization; it's gotten a lot more complicated now that we have stats.

**Comment by jcorbin** [comment]
agreed, let's let the flame graph be our guide.

**Pull request closed without merging**
