### PR TITLE
Verify that busy frames can be smoothed over

### PR DESCRIPTION
**Pull request by Raynos**
This uses the TimeSeriesCluster to create a test case that
generates 25 req/s per HyperbahnWorker.

We set the rateLimit to 10 req/s for one out of 10 Hyperbahn
workers and then assert that zero requests fail due to retries.

We also assert that the rate limiter actually kicked in.

r: @kriskowal @rf

cc @anson627 This proofs that retries on Busy solve our problem.
We still need to debug why xlate didn't do retries.

### CODE REVIEW

**Comment by anson627** [comment]
awesome! Then I can port TimeSeriesCluster to xlate and do the same test.

**Comment by Raynos** [comment]
@anson627 put me on the review for that. That's something I can help with.

**Comment by kriskowal** [comment]
Please leave some notes for future-@raynos et al, in comments or markdown, for the usage of this demo and, in particular, what makes the first bucket special.

**Comment by Raynos** [comment]
@kriskowal will do.

**Comment by Raynos** [comment]
This PR will need to be rebased in github.com/uber/hyperbahn

**Pull request closed without merging**
