### PR TITLE
Support enabling circuits for a single test service

### PR DESCRIPTION
**Pull request by kriskowal**

### CODE REVIEW

**Comment by jcorbin** [comment]
lgtm

**Comment by Raynos** [comment]
lgtm

**Comment by Raynos** [comment]
Wait; you cannot make this change in one commit. 

Hyperbahn has a tchannel dependency that is not linked by default.

**Comment by jcorbin** [comment]
subtree will split it just fine, but for least mind bending, yes it should be two PRs until we breakout / recollect all the hyperbahn code.

**Comment by Raynos** [comment]
Agreed; we should get the service proxy into the top level hyperbahn folder and out of tchannel.

There is a blocker on this that we need to rewrite relay-network / hyperbahn-cluster without it.

**Comment by kriskowal** [comment]
Landing the first part.

**Pull request merged**
