### PR TITLE
Audit and improve typed error coverage in the call frame handling paths

### PR DESCRIPTION
**Pull request by ShanniLi**
r @Raynos @kriskowal 
cc @jcorbin 
#1042

### CODE REVIEW

**Comment by Raynos** [comment]
lgtm.

**Comment by Raynos** [comment]
tests fail :(

**Comment by Raynos** [comment]
You forgot to classify lol

**Comment by ShanniLi** [comment]
@Raynos fixed. :)

**Comment by Raynos** [comment]
cool.

**Pull request merged**
