### PR TITLE
Clarify and add a new CRC checksum code

### PR DESCRIPTION
**Pull request by jcorbin**
Turns out the zlib thing we've been calling "crc32" isn't the "go fast sse" one at all; nor is it even a CRC according to wikipedia.  So:
- update doc to clarify CRC (adler vs castagnoli)
- support CRC-32C in node
- default to it

Synthetic benchmark shows that it's a win (on my macbook with confirmed hardware compiled version), we see anywhere from a 15% to 30% speedup when actual content size is involved:
```
GET large str, 1/0     rate: hi-diff:    927.23 ( 17.5%)
GET large str, 200/0   rate: hi-diff:   2311.80 ( 16.2%)
GET large str, 20000/0 rate: hi-diff:   3752.12 ( 39.4%)
GET large str, 50/0    rate: hi-diff:   2408.32 ( 17.0%)
GET small str, 1/0     rate: hi-diff:   -754.31 (-10.2%)
GET small str, 200/0   rate: hi-diff:   -353.11 ( -1.7%)
GET small str, 20000/0 rate: hi-diff:   -777.65 ( -4.1%)
GET small str, 50/0    rate: hi-diff:  -2346.44 (-10.5%)
PING, 1/0              rate: hi-diff:   -474.47 ( -6.2%)
PING, 200/0            rate: hi-diff:    -44.41 ( -0.2%)
PING, 20000/0          rate: hi-diff:   -727.27 ( -3.7%)
PING, 50/0             rate: hi-diff:   -447.02 ( -2.1%)
SET large buf, 1/0     rate: hi-diff:    509.23 (  9.3%)
SET large buf, 200/0   rate: hi-diff:   2147.07 ( 14.9%)
SET large buf, 20000/0 rate: hi-diff:   1838.62 ( 18.7%)
SET large buf, 50/0    rate: hi-diff:   1988.31 ( 13.6%)
SET large str, 1/0     rate: hi-diff:    139.37 (  2.5%)
SET large str, 200/0   rate: hi-diff:   2155.03 ( 15.1%)
SET large str, 20000/0 rate: hi-diff:   2512.70 ( 28.4%)
SET large str, 50/0    rate: hi-diff:   2039.07 ( 14.2%)
SET small buf, 1/0     rate: hi-diff:   -463.78 ( -6.4%)
SET small buf, 200/0   rate: hi-diff:  -1325.38 ( -6.1%)
SET small buf, 20000/0 rate: hi-diff:    166.26 (  0.9%)
SET small buf, 50/0    rate: hi-diff:  -2046.41 ( -9.3%)
SET small str, 1/0     rate: hi-diff:    215.40 (  3.3%)
SET small str, 200/0   rate: hi-diff:  -1345.45 ( -6.4%)
SET small str, 20000/0 rate: hi-diff:    271.34 (  1.5%)
SET small str, 50/0    rate: hi-diff:  -1806.47 ( -8.3%)
```

cc @mranney @abhinav

### CODE REVIEW

**Comment by jcorbin** [comment]
Towards python support: https://cloud.google.com/storage/docs/gsutil/addlhelp/CRC32CandInstallingcrcmod

**Comment by jcorbin** [comment]
Also fwiw, the benchmark is fairly indifferent on whether farm32 is faster/slower than sse42_crc32:
```
GET large str, 1/0     rate: hi-diff:   -316.48 ( -5.1%)
GET large str, 200/0   rate: hi-diff:     69.16 (  0.4%)
GET large str, 20000/0 rate: hi-diff:   -173.82 ( -1.3%)
GET large str, 50/0    rate: hi-diff:    -81.69 ( -0.5%)
GET small str, 1/0     rate: hi-diff:    214.95 (  3.2%)
GET small str, 200/0   rate: hi-diff:  -1148.29 ( -5.5%)
GET small str, 20000/0 rate: hi-diff:    -50.73 ( -0.3%)
GET small str, 50/0    rate: hi-diff:   1152.13 (  5.8%)
PING, 1/0              rate: hi-diff:   -321.39 ( -4.5%)
PING, 200/0            rate: hi-diff:    337.74 (  1.6%)
PING, 20000/0          rate: hi-diff:     87.92 (  0.5%)
PING, 50/0             rate: hi-diff:     43.86 (  0.2%)
SET large buf, 1/0     rate: hi-diff:   -118.91 ( -2.0%)
SET large buf, 200/0   rate: hi-diff:   -882.31 ( -5.3%)
SET large buf, 20000/0 rate: hi-diff:   -482.38 ( -4.1%)
SET large buf, 50/0    rate: hi-diff:   -673.94 ( -4.1%)
SET large str, 1/0     rate: hi-diff:    108.44 (  1.9%)
SET large str, 200/0   rate: hi-diff:    -67.13 ( -0.4%)
SET large str, 20000/0 rate: hi-diff:    758.47 (  6.7%)
SET large str, 50/0    rate: hi-diff:   -406.89 ( -2.5%)
SET small buf, 1/0     rate: hi-diff:     83.25 (  1.2%)
SET small buf, 200/0   rate: hi-diff:   1023.78 (  5.0%)
SET small buf, 20000/0 rate: hi-diff:   -613.43 ( -3.2%)
SET small buf, 50/0    rate: hi-diff:    918.62 (  4.6%)
SET small str, 1/0     rate: hi-diff:    387.99 (  5.7%)
SET small str, 200/0   rate: hi-diff:   -527.95 ( -2.7%)
SET small str, 20000/0 rate: hi-diff:     51.78 (  0.3%)
```

**Comment by abhinav** [comment]
Sounds good to me.

**Comment by jcorbin** [comment]
Going to merge without the default switch until we can get python support.

**Comment by eklitzke** [comment]
FWIW, the advantage of CRC over Farmhash isn't speed, it's that CRC functions have provable properties about the behavior of the checksum when different types of bit errors happen. From Wikipedia:

> Typically an n-bit CRC applied to a data block of arbitrary length will detect any single error burst not longer than n bits and will detect a fraction 1 − 2−n of all longer error bursts."

AFAIK for typical hash functions like Farmhash that focus on good hash value distribution, they only have probabilistic behavior in the presence of error bursts and not deterministic behavior.

**Pull request merged**
